[package]
name = "realtime-chat"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.10.1"
chrono = "0.4.40"
protobuf = "3.7.2"
serde = { version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
